@startuml
package "MessageGenSupport" {
  
  class MessageBase<T> {
    +encode<MessageEncoder, X>(self: X): auto
    +decode<MessageEncoder>(data: auto): T
  }

  struct MessageFieldMeta<idT, T> {
    {static} +MessageFieldIndexT: uint32_t = idT
    {static} +MessageFieldTypeT: T
  }
  
  struct MessageField<idT, T> extends MessageFieldMeta {
    +operator=(): T
  }

  struct DeprecatedMessageField<idT, T> extends MessageFieldMeta {
  }
  
  DeprecatedMessageField : idT : uint32_t
  DeprecatedMessageField : T : typename
  
  class Primitives {
    +Int8: MessagePrimitive<StrongNumeric<int8_t>>
    +Int16: MessagePrimitive<StrongNumeric<int16_t>>
    +Int32: MessagePrimitive<StrongNumeric<int32_t>>
    +Int64: MessagePrimitive<StrongNumeric<int64_t>>
    +UInt8: MessagePrimitive<StrongNumeric<uint8_t>>
    +UInt16: MessagePrimitive<StrongNumeric<uint16_t>>
    +UInt32: MessagePrimitive<StrongNumeric<uint32_t>>
    +UInt64: MessagePrimitive<StrongNumeric<uint64_t>>
    +Float32: MessagePrimitive<StrongNumeric<float>>
    +Float64: MessagePrimitive<StrongNumeric<double>>
    +String: MessagePrimitive<string>
    +Bytes: MessagePrimitive<vector<byte>>
  }
  @enduml